# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-17 08:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, choices=[('0', 'Django'), ('1', 'PHP'), ('2', 'Android')], max_length=200, null=True)),
                ('year', models.CharField(blank=True, choices=[('0', '1'), ('1', '2'), ('2', '3')], max_length=200, null=True)),
                ('typelist', models.CharField(blank=True, choices=[('0', 'Internship'), ('1', 'Job'), ('2', 'Project')], max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('start', models.DateField(blank=True, db_index=True, null=True)),
                ('end', models.DateField(blank=True, db_index=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('department', models.CharField(max_length=200)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
